spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/jboard

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true

    defer-datasource-initialization: true #  Hibernate 초기화 이전에 sql 스크립트를 실행할지를 설정 (data.sql을 실행시켜준다.)

  sql:
    init:
      mode: always # (data.sql을 실행시켜준다.)
      
jwt:
  header: Authorization
  secretKey: eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5NzI0Mjk4NiwiaWF0IjoxNjk3MjQyOTg2fQ.J4i-1iVJ8etLu0Ti5foDvqs3OQhWIAdiu8hyxTWnkxTEpWSUIwBmo6tKRsYy5J-5UD89u2QW65XaZHpUyoiWqg
  token-validity-in-seconds: 86400
  access:
    expiration: 360000 # 1시간(60분)
    header: Authorization
  refresh:
    expiration: 3600000 # 10시간
    header: Authorization-refresh
#  security:
#    oauth2:
#     client:
#      registration:
#       naver:
#        client-id:
#       client-secret:
#      scope:
#     redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
#    client-name: Naver
        #provider:
          #naver:
           # authorization-uri: https://nid.naver.com/oauth2.0/authorize
            #token-uri: https://nid.naver.com/oauth2.0/token
            #user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response

logging:
  level:
    org:
      hibernate:
        sql: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true